// CARRIERS ACTIONS
export const REQUEST_CARRIER = 'REQUEST_CARRIER';
export const REQUEST_CARRIERS = 'REQUEST_CARRIERS';
export const RECEIVE_CARRIER = 'RECEIVE_CARRIER';
export const RECEIVE_CARRIERS = 'RECEIVE_CARRIERS';

export const DELETE_CARRIER = 'DELETE_CARRIER';

export const SET_CARRIERS_ERRORS = 'SET_CARRIERS_ERRORS';